# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=200)),
                ('origin_iata', models.CharField(max_length=200)),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_iata', models.CharField(max_length=200)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('round_trip', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['depart_date'],
            },
        ),
    ]
