# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160306_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination_name',
            new_name='destination_city',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_name',
            new_name='origin_city',
        ),
    ]
