# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160311_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='depart_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
